### ISSUE TITLE
フォントが違います

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#1]
現在はシステムフォントが適応されています。

カンプを見ると、YuGothicとAvenir Next、Open Sansが使用されています。
なるべくそちらに合わせたほうがいいかと思います！

**Comment by foreverainn** [comment]
ロゴ、メニュー、タイトル、ボタンのフォントをAvenirNextにしました。
YuGothicとOpenSansは面倒なので変更しませんでした^^;

**Comment by k-logic563** [comment]
@kotu-kotuo 
かしこまりました。

ちなみにボタンのフォントはOpen Sansだったりします。
YuGothicはベースフォントっぽいので、global.cssにてbodyに指定してあげれば問題ないかと思われます！

**Comment by foreverainn** [comment]
フォント変更しました。
意外とすぐ終わりましたね^^

**Comment by k-logic563** [comment]
![LGTM](https://image.lgtmoon.dev/177833)
