### ISSUE TITLE
コンポーネントのテキスト表示について

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#10]
propsにて受け取るのか、childrenとして受け取るのか統一したほうがわかりやすいかもしれません！

**Comment by foreverainn** [comment]
基本的にコンポーネントのデータはPropsで受け取るようにしています。
Layoutはchildrenで受け取るのが無難だと思い、childrenを使用しています。

**Comment by k-logic563** [comment]
@kotu-kotuo 
かしこまりました！！
