### ISSUE TITLE
年が変わってもいいように

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#11]
https://github.com/kotu-kotuo/Qin-Portfolio/blob/1f712f8f26221892f3a6248491999670480743c5/src/components/Layout.tsx#L90

2022は関数を使用して自動変更できるといいですね！
`new Date().getFullYear()`

**Comment by foreverainn** [comment]
getFullYear導入しました！

**Comment by k-logic563** [comment]
@kotu-kotuo 
OKです！！
