### ISSUE TITLE
Mobile Menuのレイアウトが違う

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#13]
これは余力があれば修正してみてください！
closebuttonの位置や背景など、カンプを見ながらやってみてください。

**Comment by foreverainn** [comment]
react-burger-menuというライブラリを使っていてカスタマイズがやや面倒なのと、現在のデザインの方が使いやすいように思うので、そのままで行こうかと思います！

**Comment by k-logic563** [comment]
@kotu-kotuo 
かしこまりました！
