### ISSUE TITLE
問い合わせページのバリデーション

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#14]
バリデーションができていないです。
必須や正規表現を使用してみてください。

下記、Mantineを使用したフォームです。参考程度に！
https://mantine.dev/form/use-form/

**Comment by foreverainn** [comment]
バリデーション追加しました！

**Comment by k-logic563** [comment]
@kotu-kotuo 
お問い合わせの送信ボタンがリンクになっています!

**Comment by foreverainn** [comment]
遅くなってしまいましたが、お問合せの送信ボタン修正しました！
https://github.com/kotu-kotuo/Qin-Portfolio/commit/7091b815a76c5944306baed2ea096c034cfba388

**Comment by k-logic563** [comment]
@kotu-kotuo 
修正ありがとうございます！
バリデーションできてました。

ただ以下の点が気になります。
・メッセージが必須ではない（問い合わせの意味がなくなってしまう....）

**Comment by foreverainn** [comment]
バリデーションにrequired追加しました！
あと、messageのvalueが取得できていなかったので、values.messageに変更してみました。

**Comment by k-logic563** [comment]
@kotu-kotuo 
お疲れ様です！修正ありがとうございます！
何度もすいません。

messageの枠に空白を入れてみてください。多分バリデーションが通ってしまいます。
この場合ですが、`trim()`を使用して空白を無効にしたほうがいいです。

`values.message.trim() === ''`みたいにかけますね！

**Comment by foreverainn** [comment]
trim()追加しました！
空白でもちゃんとエラー出るようになりました。
ありがとうございます^^
