### ISSUE TITLE
バーガーメニュー

### ISSUE THREAD

**Issue by pitang1965** [kotu-kotuo/Qin-Portfolio#15]
一次開発の範囲ですが、バーガーメニューについてきになりました。
メニューがブラウザのビュー全体をカバーしないのはよいとして、例えば[Portfolio]をクリックするとポートフォリオにきちんと切り替わるのですが、メニューが閉じません。

![image](https://user-images.githubusercontent.com/47315420/189806259-6023f97c-422a-46b3-ac9f-556b8e7c1f61.png)

**Comment by foreverainn** [comment]
https://github.com/kotu-kotuo/Qin-Portfolio/commit/01823eae16d37a051766a6c59d73198b71a35294
修正しました。

**Comment by pitang1965** [comment]
確認しました。
![bitmoji](https://sdk.bitmoji.com/render/panel/ca308e5a-ee79-47f0-8c7d-2f4acd793f5b-4012260f-07f3-4d6c-a2f4-3413579a63c6-v1.png?transparent=1&palette=1&width=246)

**Comment by foreverainn** [comment]
面白い画像ですね！
