### ISSUE TITLE
useSWRのカスタムフックによりTwitter APIの仕様を背後に隠したらどうでしょうか？

### ISSUE THREAD

**Issue by pitang1965** [kotu-kotuo/Qin-Portfolio#16]
src/pages/index.tsx
```
168: <TwitterItem data={data} user={twitterData.includes.users[0]} />
```

自分のコードも同様なのですが、useSWRで取得したデータを`twitterData.includes.users[0]`のように、Twitter APIの仕様を反映してデータにアクセスしています。

これを、useSWRや/api/twitterを用いるカスタムフックを設けて、ツイートとユーザー名などを得るようにしたほうがよりよいようにも思いました。

イメージ：
```
const { tweets, twitterUser, isLoading, isError } = useTwitter();
```

**Comment by foreverainn** [comment]
作成しました。
少しコードがスッキリしましたね！

**Comment by pitang1965** [comment]
私も[カスタムフックを導入](https://github.com/pitang1965/next-portfolio/commit/dceeca7e8589b873504d1dadefc4850a03b5e81e)してみました。少しすっきりしました。

**Comment by foreverainn** [comment]
![image](https://user-images.githubusercontent.com/52486487/190055176-c0ceec0a-3c5d-469e-a405-5a4058bfa9d4.png)
