### ISSUE TITLE
Twitterの日付書式とがプロフィール画像について

### ISSUE THREAD

**Issue by pitang1965** [kotu-kotuo/Qin-Portfolio#17]
src/components/Item/TwitterItem.tsx

これは仕様の問題で、対応せず本issueはクローズしてもらってかまわないですが、少し気になったのでご参考まで。

プロフィール画像が、/kaja.pngで、日付形式が"MM月DD日"に固定となっています。

このため、Twitterのプロフィール画像を変更したなら、本プロジェクトも変更が必要になります。
また、年が変わって昨年のツイートを表示することになった場合、年は表示されません。

**Comment by foreverainn** [comment]
日付形式についてですが、デザインが年を含めていませんし、役割としても飾りの意味合いが強いと思うのであまり正確に日時を示す必要はないのではと思います。
プロフィール画像についてですが、最近メイドインアビスが面白いので作中のキャラクターであるマジカジャさんにしていたのですが、ピータンさんのおっしゃられるように保守性に問題があるので変更しました。

**Comment by pitang1965** [comment]
そうですね。あまり日付形式重要でないかもしれません。
私はTwitterと同じように、60分未満なら「45分」などと表示するようにしちゃいました。

**Comment by foreverainn** [comment]
![image](https://user-images.githubusercontent.com/52486487/190055007-98971ca7-47dd-45bf-8ed5-c3cc6336b891.png)
