### ISSUE TITLE
Linkボタンの使い方について

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#3]
https://github.com/kotu-kotuo/Qin-Portfolio/blob/1f712f8f26221892f3a6248491999670480743c5/src/components/ButtonBlack.tsx#L21-L25
この書き方だと、aタグにhrefが反映されません。

下記のようにすれば反映されます。
```
<Link href={`/${link}`} passHref> 
   <Button className="rounded-full bg-gray-900" component="a"> 
     {text}
   </Button> 
 </Link> 
```

**Comment by k-logic563** [comment]
理由は以下のページに書かれています。参考程度に！
https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

**Comment by k-logic563** [comment]
他のリンクタグも修正できればお願いします。

**Comment by foreverainn** [comment]
リンクの修正しました。
他のリンクタグは特に問題がないように思ったので、修正しませんでした。

**Comment by k-logic563** [comment]
@kotu-kotuo 
確認しました！

下記、aタグ必要ないかと思われます。
https://github.com/kotu-kotuo/Qin-Portfolio/blob/5bb0f6fc6cd06e012c518c7f07b6398dd89b3f1d/src/components/ButtonBlack.tsx#L15-L24

こんなふうにButtonコンポーネントにhrefやら設定できます。
https://mantine.dev/core/button/#polymorphic-component

**Comment by foreverainn** [comment]
修正しました。
https://github.com/kotu-kotuo/Qin-Portfolio/commit/1fb41ded59b9f4cd44921b7623268c915dac48f7

**Comment by k-logic563** [comment]
@kotu-kotuo 
![LGTM](https://image.lgtmoon.dev/177833)
