### ISSUE TITLE
コンポーネントでのクラスについて

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#4]
https://github.com/kotu-kotuo/Qin-Portfolio/blob/1f712f8f26221892f3a6248491999670480743c5/src/components/ButtonBlack.tsx#L13-L27

今の場合だと、もしボタンを左寄せにする必要があった場合困ります。
`.text-center`クラスは親コンポーネントで付けたほうがいいです。（コンポーネントは基本最小限のスタイリングに止めるといいかもです）

**Comment by foreverainn** [comment]
コンポーネントからレイアウトの要素を分離させました。

**Comment by k-logic563** [comment]
@kotu-kotuo 
修正ありがとうございます！

https://github.com/kotu-kotuo/Qin-Portfolio/blob/5bb0f6fc6cd06e012c518c7f07b6398dd89b3f1d/src/components/ButtonBlack.tsx#L13-L32

こちらはdivで囲む必要はなく、以下のように書き換えることができます！
```
externalLink ? (
      <Button className="rounded-full bg-gray-900 text-white">
        <a
          href={link}
          target="_blank"
          rel="noopener noreferrer"
          className="font-main text-white no-underline"
        >
          {text}
        </a>
      </Button>
    ) : (
      <Link href={`/${link}`} passHref>
        <Button className="rounded-full bg-gray-900 font-main" component="a">
          {text}
        </Button>
      </Link>
    )
```

**Comment by foreverainn** [comment]
修正しました！
こんな書き方もあるんですね、勉強になります。

**Comment by k-logic563** [comment]
@kotu-kotuo 
![LGTM](https://image.lgtmoon.dev/177833)
