### ISSUE TITLE
ヘッダー、コンテンツ、フッターのレイアウトについて

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#6]
aboutページではフッターが画面下に位置せず、コンテンツにくっついています。
以下を参考にスタイリングしてみてください。
https://zenn.dev/catnose99/articles/a873bbbe25b15b

**Comment by foreverainn** [comment]
修正しました。
参考リンクありがとうございます^^

**Comment by k-logic563** [comment]
@kotu-kotuo 
修正ありがとうございます。

多分、ここの`flex-1`がなくても機能するかと思われます。
https://github.com/kotu-kotuo/Qin-Portfolio/blob/5bb0f6fc6cd06e012c518c7f07b6398dd89b3f1d/src/components/Layout.tsx#L84

**Comment by foreverainn** [comment]
修正しました。

**Comment by k-logic563** [comment]
@kotu-kotuo 
![LGTM](https://image.lgtmoon.dev/177833)
