### ISSUE TITLE
ここはmicroCMSの本文がくるかもしれないので

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#7]
https://github.com/kotu-kotuo/Qin-Portfolio/blob/1f712f8f26221892f3a6248491999670480743c5/src/pages/blog/%5Bcid%5D.tsx#L13-L16

以下のようにすればHTML文字列が反映されるようになります。
`<div dangerouslySetInnerHTML={{ __html: '....' }} />`

**Comment by foreverainn** [comment]
修正しました。

**Comment by k-logic563** [comment]
@kotu-kotuo 
OKです！！
