### ISSUE TITLE
components内のファイルについて

### ISSUE THREAD

**Issue by k-logic563** [kotu-kotuo/Qin-Portfolio#9]
ディレクトリ分けをしたほうがいいかもしれません！
例えばLayoutなら `Layout/index.tsx` など

**Comment by foreverainn** [comment]
コンポーネントをElement, Item, Layoutに整理してみました。

**Comment by k-logic563** [comment]
@kotu-kotuo 
整理できて見やすくなりました！
![LGTM](https://image.lgtmoon.dev/177833)
